import { test, expect } from "bun:test";
import { Catalog } from "../src/catalog";
import { Decoder, encode } from "../src/framing";
import { DEFAULT_POLICY, enabled, TOOLS, type Page } from "../src/shared";
import { equalSecret } from "../src/local";
import { newer, extract } from "../src/installer";
import { zipSync, strToU8 } from "fflate";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const page = (): Page => ({ key: "page", documentId: "document", tabId: 1, frameId: 0, origin: "https://example.com", url: "https://example.com/orders?secret=1", title: "Orders", active: true, enabled: true, revision: 1, tools: [{ key: "k1", name: "get_order", description: "Read an order", inputSchema: { type: "object", properties: { id: { type: "string" } }, required: ["id"] } }] });
test("native framing handles fragmented and coalesced messages", () => { const bytes = Buffer.concat([encode({ a: "text" }), encode({ b: 2 })]); const d = new Decoder(); expect(d.push(bytes.subarray(0, 3))).toEqual([]); expect(d.push(bytes.subarray(3, 7))).toEqual([]); expect(d.push(bytes.subarray(7))).toEqual([{ a: "text" }, { b: 2 }]); });
test("invalid frame lengths are rejected", () => { expect(() => new Decoder().push(Buffer.alloc(4))).toThrow(); });
test("secret comparison rejects unicode without exceptions", () => { expect(equalSecret("a".repeat(64), "a".repeat(64))).toBe(true); expect(equalSecret("\u00e9".repeat(64), "a".repeat(64))).toBe(false); });
test("exact origin defaults and overrides", () => { const p = { ...DEFAULT_POLICY, sites: { "https://example.com": true } }; expect(enabled(p, undefined, "https://example.com")).toBe(true); expect(enabled(p, undefined, "http://example.com")).toBe(false); expect(enabled(p, { origin: "https://example.com", enabled: false }, "https://example.com")).toBe(false); });
test("disabled contexts never appear, URLs drop query and fragment", () => { const c = new Catalog(), p = page(); p.enabled = false; c.upsert("one", p); expect(c.contexts()).toHaveLength(0); p.enabled = true; c.upsert("one", p); expect(c.contexts()[0].url).toBe("https://example.com/orders"); });
test("references bind document, revision, channel and exposure", () => { const c = new Catalog(), p = page(); c.upsert("one", p); const old = c.search({}).tools[0].toolRef; p.documentId = "new"; c.upsert("one", p); expect(() => c.tool(old)).toThrow(); const next = c.search({}).tools[0].toolRef; p.enabled = false; c.upsert("one", p); expect(() => c.tool(next)).toThrow(); p.enabled = true; c.upsert("two", p); c.remove("two"); expect(c.contexts()).toHaveLength(0); });
test("descriptions and calls validate original schemas", () => { const c = new Catalog(); c.upsert("one", page()); const ref = c.search({}).tools[0].toolRef; expect(c.describe([ref]).tools[0].name).toBe("get_order"); expect(() => c.validate(ref, { id: "x" })).not.toThrow(); expect(() => c.validate(ref, { id: 1 })).toThrow(); });
test("meta tools are invariant across catalogue state", () => { const before = JSON.stringify(TOOLS), c = new Catalog(); c.upsert("one", page()); c.remove("one"); expect(JSON.stringify(TOOLS)).toBe(before); });
test("cursor invalidates on metadata/catalogue changes", () => { const c = new Catalog(), p = page(); p.tools.push({ ...p.tools[0], key: "k2", name: "get_customer" }); c.upsert("one", p); const cursor = c.search({ limit: 1 }).nextCursor!; p.revision++; c.upsert("one", p); expect(() => c.search({ limit: 1, cursor })).toThrow(); });
test("release comparisons never allow downgrade", () => { expect(newer("1.1.0", "1.0.9")).toBe(true); expect(newer("1.0.0", "1.0.0")).toBe(false); expect(() => newer("../x", "1.0.0")).toThrow(); });
test("archive traversal is rejected before extraction", () => { const temp = mkdtempSync(join(tmpdir(), "webmcp-zip-")); try { const zip = zipSync({ "../escape": strToU8("bad") }); expect(() => extract(zip, temp)).toThrow(); } finally { rmSync(temp, { recursive: true, force: true }); } });
